### ISSUE TITLE
PyTest - Solver not available

### ISSUE THREAD

**Issue by cheind** [cheind/py-motmetrics#80]
Hey @jvlmdr,

all the solver backends are now required to run pytest. I guess that's fine but we should note that in either the ReadMe or in another place. I don't think adding this to the requirements is a good idea, since the average user usually does not want to have so many solvers installed.

**Comment by jvlmdr** [comment]
Yep, I agree that we shouldn't add them to requirements.

Actually, I just recently modified `test_lap.py` so that it only uses `lap.available_solvers` to run the tests. It issues a warning if one of the "desired solvers" for the tests was not in `lap.available_solvers`, but all the tests will pass. See here: https://github.com/cheind/py-motmetrics/blob/37ec1ac33bf76cf5cde02e8d1902e2e2b0c245f2/motmetrics/tests/test_lap.py#L15-L22

**Comment by cheind** [comment]
ah, nice! then we can close this I guess.
