### ISSUE TITLE
Overall MOTP can be NaN

### ISSUE THREAD

**Issue by haofengac** [cheind/py-motmetrics#95]
I am encountering the problem of the overall MOTP being NaN. It seems that if the tracker completely misses a single category (in this case num_detections is 0 and MOTP for this single class is NaN), the aggregated overall MOTP is also NaN. This behavior might not be desirable.

https://github.com/cheind/py-motmetrics/blob/333495ea95b33ab0218885a2e95cbcfd86a4399e/motmetrics/metrics.py#L507

This line of code only needs to be called if `v['num_detections'] > 0`. A simple if statement can fix this issue.

**Comment by cheind** [comment]
this likely to be related to #109 and expected behaviour.

**Comment by cheind** [comment]
Closing this question as resolved

**Comment by Spritea** [comment]
I also think the overall MOTP should avouid being NaN, though the MOTP of a specific sequence could be NaN.

Just like #109 , Precision/Recall for single sequence could be NaN due to definition, but the overall Precision/Recall is not NaN.

This would enable us to compare different trackers on MOTP metric.
